version: '3.7'
services:
  db:
    image: library/postgres:13.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef